language: php
sudo: false
php:
- 7.4
- 8.0
- 8.1
install:
- composer config -a -g http-basic.repo.magento.com $MAGE_USER $MAGE_PASS
- composer config repositories.meqp git https://github.com/magento/marketplace-eqp
- composer config repositories.meqp2 composer https://repo.magento.com/
- composer require --dev magento/marketplace-eqp:1.*
- php vendor/bin/phpcs --config-set installed_paths vendor/magento/marketplace-eqp/
script:
- php vendor/bin/phpcs --ignore=./vendor/*,*/Unit/* --standard=MEQP2 --extensions=php,phtml,js
  .
env:
  global:
  - secure: MYgMtw5QE+rllr//T+rF10YAHqHtoNRnw3rqaL3Dm6+AU/IRPyLmFauYbHF7AbQ8jEP08o87IpTgoQCAGmhpU4C2YjkR3FhmRbM5sR1b+tfU+RevPekzGB0+kKuMZqdCPL0xtFOVkPWdat3Ag/O1Sp1xQC5LwTfpT3EiKLMeL2srgjIleH2EW3DxC/rQAk6N2Y6oKrpxgL1iiH9bJrxIZXEnxLLFlC0KMtJmWQ/ZHHh/dk2kll64g7O75abE4hlmwuuphEkwNjnFSk9lIge655xapmL9MWUwjXXiQTLW8IFhFr09sJGLDdUyh59fqD9zyFHnugRNVTyIu90SUD8bF4IWU+EHfTr0c1+VIEv/yvLqQsfHj454T2E5Ki3aKPdL5T5WB5F4Dj/J+G6fDS9j0MPchOA9YrnBTVbE71gkftPtskyKuar9sgdjyGFfAVUdyj9SIjfrkrug+DUu6cG+JhXgV8g1/Smw6c7tgX8rVBDBj/fJElC+c94JcjQ47Yr+kSMYHG4CLUD3MPAhVLgI1qMLQboppmx9YNzZ2Y+dY5iAdCuOUuwnR/KQ6nTVcKqHbo9yVGGYtvKKeOwzYpSUD8scTew5DHi2CZ6y8iCJXod1yHe3i/NxkzyEoPJt+gZxKtBjnPmeF7+gpfcbtBU5AlvrddJv4F3JD/eU2N7eU3w=
  - secure: toCHmJG9LoCu2lFq2Kqzo1j60+xXlvRW5Iwtf/tk31ZD0U2gyf/cziN2J4DDoqbPkIBzzVHpm0BYAVpM9O0/M44otHyWyO5mQDlMCMjbNHg+Q04Dfw0FtymN63XXfZVS6U06DGoV/RUDPNjEdRstTkt4a0pvqNOVsVqBab6d2QN243DrLPLFMIG9OJV5QZ9Mq7PdudDKDNgOJOWPhBk71ou7Fig6MUhXqtNeuKMbRsjpIgT2uH/ayfVDCMc0vxtiBd+79T6gTzgkLP4CGPRJs8k7Uvhz5rWgSGd++Hwk5J0dg6FBlUIHf8CWojJi6q2yjOhwB7IITMqvTjeKgh8Kl5rTVc2f9eghLaJB+borSST/6Y2zxLOlnoWjQwaIHNqRdFUt2GtS73iNvA7F/PW/2q1/TIcyrBly4n+QOyv485ygXf2lSBxIoKpR5bBaZ1o638HI+W1dL6AQ+R/uvWTUPdlbLcekO9RPL1yFSLUaQI9wNMH79JwlGJpMChe5hCGRScs5VfO7auibnzvHQJ6GxOf0z5ql7EIw6Jnf+bhQjVrP/jStIW1mOqZbtLxLGUK8IdjGAby0EmPspS93arq1wuZOcebZYDGEsnu9PPcvADfz+khskIscGDz1jtQa30xJSNUd7SzZdPpuxkWQHNBT+HR1+eYe7Agv+FJYkl+90Fw=
