name: "Test"

on:
  pull_request:
    branches: [master]

jobs:
  static_code_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpcs, cs2pr

      - name: Install and setup Magento 2 coding standard
        run: |
          vendor_path=$(composer global config vendor-dir --absolute) && \
          composer global require magento/magento-coding-standard && \
          phpcs --config-set installed_paths "$vendor_path/magento/magento-coding-standard/,$vendor_path/phpcompatibility/php-compatibility/"

      - name: Run phpcs
        run: phpcs -q --report=checkstyle --standard=Magento2 . | cs2pr